project:
  type: book
book:
  title: "scRNA-seq analysis report"
  author: "WQR"
  date: "2023/12/1"
  chapters:
    - index.qmd
    - CreateArrowFiles.qmd
    - DoubletInference.qmd
    - CreateArchR.qmd
    - DimensionalityReduction.qmd
    - Clustering.qmd
    - Embeddings.qmd
    - GeneScores.qmd
    - Integrate_scRNA-seq.qmd
    - Pseudo-bulkReplicates.qmd
    - CallingPeaks.qmd
format:
  html:
    theme: cosmo
