# 学习ArchR {.unnumbered}
Learn ArchR for scATAC-seq

**翻译ArchR完整手册**

## install
```{r eval=FALSE}
if (!requireNamespace("devtools", quietly = TRUE))
  install.packages("devtools")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
# 升级BiocManager
BiocManager::install(version = "3.18")

devtools::install_github(
  "GreenleafLab/ArchR",
  ref = "master",
  repos = BiocManager::repositories()
)
library(ArchR)
ArchR::installExtraPackages()

install.packages("hexbin")
```

```{r eval=FALSE,echo=FALSE}
# BiocManager::install("GreenleafLab/ArchR")

# 设置GitHub API
# usethis::edit_r_environ()
# "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"
# # 设置Bioconductor清华镜像
# BiocManager::repositories()
# options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
# options(timeout = 1e3)
# BiocManager::install(
#   "motifmatchr",
# #  ask = FALSE,
#   site_repository = 
# )
# # 修改etc/Rprofile.site
# options(download.file.method = "libcurl")
# options(url.method = "libcurl")
# # 升级biocmanager
# BiocManager::valid()
# update.packages()
# ## 先卸载先前的安装控制程序
# remove.packages(c("BiocManager", "BiocVersion"))

## 再安装新版程序
# install.packages("BiocManager")
# BiocManager::install(update=TRUE, ask=FALSE)

# 安装Signac--------------------------------------------------------------------
# needed to automatically install Bioconductor dependencies
setRepositories(ind = 1:3)
install.packages("Signac")

#-------------------------------------------------------------------------------
# 安装pbmcMultiome数据集，整合scRNA和scATAC
library(SeuratData)
## install the dataset and load requirements
## InstallData("pbmcMultiome") # nolint: commented_code_linter.
options(timeout = 1000)
InstallData("pbmcMultiome.SeuratData")
```

## 课程信息
本教程在以下指定日期进行。`Sys.Date()`

运行时的 sessionInfo() 是：`sessionInfo()`